name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Check out code
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build the project
      - name: Build
        run: npm run build

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t tap-game:latest .

      # Log in to Google Container Registry
      - name: Login to Google Container Registry
        run: echo "${GOOGLE_CREDENTIALS}" | base64 --decode > client-secret.json
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Grant execute permission to the key file
        run: chmod +x client-secret.json

      - name: Set up gcloud
        uses: google-auth/setup-gcloud@v1
        with:
          service_account_key: client-secret.json

      # Push the image to Google Container Registry
      - name: Push Docker image
        run: |
          docker tag my-image:latest gcr.io/[PROJECT-ID]/my-image:latest
          gcloud docker -- push gcr.io/[PROJECT-ID]/my-image:latest
